export const ResponseCode = {
  CODE_SUCCESS: 0,
  CODE_PERMISSION: 1,
  CODE_NOT_FOUND: 2,
  CODE_ALREADY_EXIST: 3,
  CODE_BUSINESS: 4,
  CODE_EXPIRED: 8888,
  CODE_INTERNAL_ERROR: 9999
}

export const Status = {
  ACTIVE: 'ACTIVE',
  IN_ACTIVE: 'IN_ACTIVE',
  ALL: 'ALL'
}

export const VoucherType = {
  PERCENT: 'PERCENT',
  MONEY: 'MONEY'
}

export const Role = {
  ROLE_CUSTOMER: 'ROLE_CUSTOMER',
  ROLE_STAFF_SALES: 'ROLE_STAFF_SALES',
  ROLE_STAFF_WAREHOUSE_MANAGEMENT: 'ROLE_STAFF_WAREHOUSE_MANAGEMENT',
  ROLE_SUPER_ADMIN: 'ROLE_SUPER_ADMIN'
}

